<?php

namespace app\admin\controller;

use think\Controller;

class Base extends Controller
{
    // 公共控制器
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('?admin.id')){
            $this->redirect('admin/index/login');
        }
    }


}
