<?php

namespace app\admin\controller;

use PHPMailer\PHPMailer\PHPMailer;
use think\Controller;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('?admin.id')){
            $this->redirect('admin/home/index');
        }
    }
    //后台登录
    public function login(){

        if(request()->isAjax()){

            $data =[
                'username' => input('post.username'),
                'password' => input('post.password'),
            ];

            $result =  model('Admin')->login($data);

            if($result == 1){
                $this->success('登录成功','admin/home/index');
            }else{

                $this->error($result);
            }
        }

        return view();
    }

    //注册
    public function register(){

        if(request()->isAjax()){

            $data =[
                'username' => input('username'),
                'password' => input('password'),
                'conpass'  => input('conpass'),
                'nickname' => input('nickname'),
                'email'    => input('email')
            ];
            $result = model('Admin')->register($data);

            if($result == 1){
                $this->success('注册成功','admin/index/login');
            } else{
                $this->error($result);
            }
        }
        return view();
    }

    //忘记密码
    public function forget(){

        if($this->request->isAjax()) {


            $code = mt_rand(1000,9999);
            session('code',$code);
            $to = input('email');
            $result = sendMail($to,'验证码', $code);
            if($result){
                $this->success('验证码发送成功');
            }else{
                $this->error('验证码发送失败');
            }
        }
        return view();
    }

    //重置密码
    public function reset(){

        $data = [
            'code' => input('post.code'),
            'email' => input('email'),
        ];

        $result = model('Admin')->reset($data);
        if($result == 1){
            $this->success('密码重置成功,去邮箱查看新密码');
        } else {
            $this->error($result);
        }
    }
}
