<?php

namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
    //使用共享视图
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cates = model('Cate')->order('sort','ase')->select();
        $webInfo = model('System')->find();
        $topArticles = model('Article')->where('is_top',1)
            ->order('create_time','desc')->limit(10)->select();

        $viewData = [
            'cates' => $cates,
            'webInfo' => $webInfo,
            'topArticles' =>$topArticles,
        ];

        $this->view->share($viewData);
    }
}
